### Run test remotely
# @timeout 120
POST http://77.234.215.138:34321/run
Content-Type: application/json

{
  "serviceName": "{{serviceName}}",
  "token": "{{token}}",
  "branch": "lab-4",
  "accounts": "acc-18",
  "ratePerSecond": 200,
  "testCount": 6000,
  "processingTimeMillis": 3000,
  "onPremises": true
}

### Stop running test to save credits
# @timeout 120
POST http://77.234.215.138:31234/test/stop/{{serviceName}}